#!/usr/bin/env node

const fs = require('fs');
const cheerio = require('cheerio');

process.stdout.write(`
  <gpx>
    <trk>
      <trkseg>
        ${process.argv.slice(2).map(inputFile => {
          const inputGpx = fs.readFileSync(inputFile);
          const inputGpx$ = cheerio.load(inputGpx, {xmlMode: true});
          return inputGpx$.xml(inputGpx$('trkpt'));
        })}
      </trkseg>
    </trk>
  </gpx>
`);
